appURL=https://www.insurancedekho.com/
allure.bat serve ../../allure-results

screenshotPath=./screenshots


# --- SMTP / Email Settings (Gmail) ---
email.enabled=true
smtp.host=smtp.gmail.com
smtp.port=587
smtp.username=ashish93343@gmail.com
smtp.password=ieyh fojs qwrm kgmm
smtp.auth=true
smtp.starttls=true

email.from=ashish93343@gmail.com
email.to=ishak93343@gmail.com
email.subject=InsuranceDekho Automation Execution Report

#testdata
wrongMobileNo=98765
name=john
dob=01012001
mobile=9876543210
renewMobile=9876546111